export interface Card {
  name: string;
  weight: number;
}

export const cards: Card[] = [
  { name: "Carta Maya", weight: 15 },
  { name: "Carta Abelha Rainha", weight: 15 },
  { name: "Carta Serpente Suprema", weight: 15 },
  { name: "Carta Flor do Luar", weight: 15 },
  { name: "Carta Drake", weight: 15 },
  { name: "Carta Freoni", weight: 15 },
  { name: "Carta Hatii", weight: 15 },
  { name: "Carta Eddga", weight: 15 },
  { name: "Carta Dracula", weight: 15 },
  { name: "Carta Cavaleiro da Tempestade", weight: 15 },
  { name: "Carta Osíris", weight: 15 },
  { name: "Carta General Tartaruga", weight: 15 },
  { name: "Carta Faraó", weight: 15 },
  { name: "Carta Lady Tanee", weight: 10 },
  { name: "Carta Samurai Encarnado", weight: 10 },
  { name: "Carta Doppelganger", weight: 10 },
  { name: "Carta Lady Branca", weight: 10 },
  { name: "Carta Boitata", weight: 10 },
  { name: "Carta Gorynych", weight: 10 },
  { name: "Carta Rei Poring", weight: 10 },
  { name: "Carta Besouro-Ladrão Dourado", weight: 10 },
  { name: "Carta Tao Gunka", weight: 10 },
  { name: "Carta Orc Herói", weight: 10 },
  { name: "Carta Fenrir", weight: 10 },
  { name: "Carta Egnigem Cenia", weight: 8 },
  { name: "Carta Senhor dos Orcs", weight: 8 },
  { name: "Carta Senhor dos Mortos", weight: 8 },
  { name: "Carta Vesper", weight: 5 },
  { name: "Carta Bafomé", weight: 5 },
  { name: "Carta Senhor das Trevas", weight: 5 },
  { name: "Carta RSX-0806", weight: 5 },
  { name: "Carta Polvo Gigante", weight: 5 },
  { name: "Carta Amon-Ra", weight: 5 },
  { name: "Carta Detardeurus", weight: 5 },
  { name: "Carta Cabra da Peste", weight: 5 },
  { name: "Carta Cabra Safado", weight: 5 },
  { name: "Carta Cabra Macho", weight: 5 },
  { name: "Carta Atroce", weight: 5 },
  { name: "Carta Rei da Noite", weight: 3 },
  { name: "Carta Réquiem de Marfim", weight: 3 },
  { name: "Carta Groteskia", weight: 3 },
  { name: "Carta Drogon/Sombra do Guardião", weight: 3 },
  { name: "Carta Memória de Thanatos", weight: 3 },
  { name: "Carta Skoll", weight: 3 },
  { name: "Carta Venomorfo Perfeito", weight: 3 },
  { name: "Carta Amdarais", weight: 3 },
  { name: "Carta Celine Kimi", weight: 3 },
  { name: "Carta Bispo Decadente", weight: 3 },
  { name: "Carta Kiel-D-01", weight: 3 },
  { name: "Carta Pesar Noturno", weight: 3 },
  { name: "Carta Presa Flamejante", weight: 3 },
  { name: "Carta Detardeurus Esquelético", weight: 3 },
  { name: "Carta Naght Sieger", weight: 2 },
  { name: "Carta Rainha Scaraba", weight: 2 },
  { name: "Carta Kraken", weight: 2 },
  { name: "Carta Ktullanux", weight: 2 },
  { name: "Carta Ifrit", weight: 2 },
  { name: "Carta Valquíria Randgris", weight: 2 },
  { name: "Carta Rainha Verme", weight: 2 },
  { name: "Carta Beelzebub", weight: 2 },
  { name: "Carta Satan Morroc", weight: 2 },
  { name: "Carta Amdarais Corrompido", weight: 2 },
  { name: "Carta Avatar de Freya", weight: 2 },
  { name: "Carta Lorde Seyren", weight: 1 },
  { name: "Carta Mestre Ferreiro Howard", weight: 1 },
  { name: "Carta Algoz Eremes", weight: 1 },
  { name: "Carta Arquimaga Kathryne", weight: 1 },
  { name: "Carta Sumo Margaretha", weight: 1 },
  { name: "Carta Atiradora Cecil", weight: 1 },
  { name: "Carta Paladino Randel", weight: 1 },
  { name: "Carta Criador Flamel", weight: 1 },
  { name: "Carta Cigana Trentini", weight: 1 },
  { name: "Carta Professora Celia", weight: 1 },
  { name: "Carta Mestre Chen", weight: 1 },
  { name: "Carta Menestrel Alphoccio", weight: 1 },
  { name: "Carta Desordeira Gertie", weight: 1 },
  { name: "Carta Verão Ancestral", weight: 1 },
  { name: "Carta Outono Ancestral", weight: 1 },
  { name: "Carta Inverno Ancestral", weight: 1 },
  { name: "Carta Primavera Ancestral", weight: 1 },
  { name: "Carta Gioia", weight: 1 }
];
