export enum sc_type {
  SC_NONE = -1,
  //First we enumerate common status ailments which are often used around.
  SC_STONE = 0,
  SC_COMMON_MIN = 0, // begin
  SC_FREEZE,
  SC_STUN,
  SC_SLEEP,
  SC_POISON,
  SC_CURSE,
  SC_SILENCE,
  SC_CONFUSION,
  SC_BLIND,
  SC_BLOODING,
  SC_DPOISON, //10
  SC_FEAR,
  SC_COLD,
  SC_BURNING,
  SC_DEEP_SLEEP,
  SC_COMMON_MAX = 14, // end

  //Next up, we continue on 20, to leave enough room for additional "common" ailments in the future.
  SC_PROVOKE = 20,
  SC_ENDURE,
  SC_TWOHANDQUICKEN,
  SC_CONCENTRATION,
  SC_HIDING,
  SC_CLOAKING,
  SC_ENCHANTPOISON,
  SC_POISONREACT,
  SC_QUAGMIRE,
  SC_ANGELUS,
  SC_BLESSING, //30
  SC_CRUCIS,
  SC_INC_AGI,
  SC_DEC_AGI,
  SC_SLOWPOISON,
  SC_IMPOSITIO,
  SC_SUFFRAGIUM,
  SC_ASPERSIO,
  SC_BENEDICTIO,
  SC_KYRIE,
  SC_MAGNIFICAT, //40
  SC_GLORIA,
  SC_LEXAETERNA,
  SC_ADRENALINE,
  SC_WEAPONPERFECT,
  SC_OVERTHRUST,
  SC_MAXIMIZEPOWER,
  SC_TRICKDEAD,
  SC_SHOUT,
  SC_ENERGYCOAT,
  SC_BROKENARMOR, //50 - NOTE: These two aren't used anywhere, and they have an icon...
  SC_BROKENWEAPON,
  SC_ILLUSION,
  SC_WEIGHTOVER50,
  SC_WEIGHTOVER90,
  SC_ATTHASTE_POTION1,
  SC_ATTHASTE_POTION2,
  SC_ATTHASTE_POTION3,
  SC_ATTHASTE_INFINITY,
  SC_MOVHASTE_HORSE,
  SC_MOVHASTE_INFINITY, //60
  SC_PLUSATTACKPOWER,
  SC_PLUSMAGICPOWER,
  SC_WEDDING,
  SC_SLOWDOWN,
  SC_ANKLESNARE,
  SC_KEEPING,
  SC_BARRIER,
  SC_NOEQUIPWEAPON,
  SC_NOEQUIPSHIELD,
  SC_NOEQUIPARMOR, //70
  SC_NOEQUIPHELM,
  SC_PROTECTWEAPON,
  SC_PROTECTSHIELD,
  SC_PROTECTARMOR,
  SC_PROTECTHELM,
  SC_AUTOGUARD,
  SC_REFLECTSHIELD,
  SC_SPLASHER,
  SC_PROVIDENCE,
  SC_DEFENDER, //80
  SC_MAGICROD,
  SC_SPELLBREAKER,
  SC_AUTOSPELL,
  SC_SIGHTTRASHER,
  SC_AUTOBERSERK,
  SC_SPEARQUICKEN,
  SC_AUTOCOUNTER,
  SC_SIGHT,
  SC_SAFETYWALL,
  SC_RUWACH, //90
  SC_EXTREMITYFIST,
  SC_EXPLOSIONSPIRITS,
  SC_COMBOATTACK,
  SC_BLADESTOP_WAIT,
  SC_BLADESTOP,
  SC_PROPERTYFIRE,
  SC_PROPERTYWATER,
  SC_PROPERTYWIND,
  SC_PROPERTYGROUND,
  SC_VOLCANO, //100,
  SC_DELUGE,
  SC_VIOLENTGALE,
  SC_SUB_WEAPONPROPERTY,
  SC_ARMOR,
  SC_ARMORPROPERTY,
  SC_NOCHAT,
  SC_BABY,
  SC_AURABLADE,
  SC_PARRYING,
  SC_LKCONCENTRATION, //110
  SC_TENSIONRELAX,
  SC_BERSERK,
  SC_FURY,
  SC_GOSPEL,
  SC_ASSUMPTIO,
  SC_BASILICA,
  SC_GUILDAURA,
  SC_MAGICPOWER,
  SC_EDP,
  SC_TRUESIGHT, //120
  SC_WINDWALK,
  SC_MELTDOWN,
  SC_CARTBOOST,
  SC_CHASEWALK,
  SC_SWORDREJECT,
  SC_MARIONETTE_MASTER,
  SC_MARIONETTE,
  SC_PROPERTYUNDEAD,
  SC_JOINTBEAT,
  SC_MINDBREAKER, //130
  SC_MEMORIZE,
  SC_FOGWALL,
  SC_SPIDERWEB,
  SC_DEVOTION,
  SC_SACRIFICE,
  SC_STEELBODY,
  SC_ORCISH,
  SC_STORMKICK_READY,
  SC_DOWNKICK_READY,
  SC_TURNKICK_READY, //140
  SC_COUNTERKICK_READY,
  SC_DODGE_READY,
  SC_RUN,
  SC_PROPERTYDARK,
  SC_ADRENALINE2,
  SC_PROPERTYTELEKINESIS,
  SC_KAIZEL,
  SC_KAAHI,
  SC_KAUPE,
  SC_ONEHANDQUICKEN, //150
  SC_PRESERVE,
  SC_GDSKILL_BATTLEORDER,
  SC_GDSKILL_REGENERATION,
  SC_DOUBLECASTING,
  SC_GRAVITATION,
  SC_OVERTHRUSTMAX,
  SC_LONGING,
  SC_HERMODE,
  SC_TAROTCARD,
  SC_CR_SHRINK, //160
  SC_WZ_SIGHTBLASTER,
  SC_DC_WINKCHARM,
  SC_RG_CCONFINE_M,
  SC_RG_CCONFINE_S,
  SC_DANCING,
  SC_ARMOR_PROPERTY,
  SC_RICHMANKIM,
  SC_ETERNALCHAOS,
  SC_DRUMBATTLE,
  SC_NIBELUNGEN, //170
  SC_ROKISWEIL,
  SC_INTOABYSS,
  SC_SIEGFRIED,
  SC_WHISTLE,
  SC_ASSNCROS,
  SC_POEMBRAGI,
  SC_APPLEIDUN,
  SC_MODECHANGE,
  SC_HUMMING,
  SC_DONTFORGETME, //180
  SC_FORTUNE,
  SC_SERVICEFORYOU,
  SC_STOP, //Prevents inflicted chars from walking. [Skotlex]
  SC_STRUP,
  SC_SOULLINK,
  SC_COMA, //Not a real SC_, it makes a char's HP/SP hit 1.
  SC_CLAIRVOYANCE,
  SC_INCALLSTATUS,
  SC_CHASEWALK2,
  SC_INCAGI, //190
  SC_INCVIT,
  SC_INCINT,
  SC_INCDEX,
  SC_INCLUK,
  SC_INCHIT,
  SC_INCHITRATE,
  SC_INCFLEE,
  SC_INCFLEERATE,
  SC_INCMHPRATE,
  SC_INCMSPRATE, //200
  SC_INCATKRATE,
  SC_INCMATKRATE,
  SC_INCDEFRATE,
  SC_FOOD_STR,
  SC_FOOD_AGI,
  SC_FOOD_VIT,
  SC_FOOD_INT,
  SC_FOOD_DEX,
  SC_FOOD_LUK,
  SC_FOOD_BASICHIT, //210
  SC_FOOD_BASICAVOIDANCE,
  SC_BATKFOOD,
  SC_WATKFOOD,
  SC_MATKFOOD,
  SC_SCRESIST, //Increases resistance to status changes.
  SC_XMAS, // Xmas Suit [Valaris]
  SC_WARM, //SG skills [Komurka]
  SC_SUN_COMFORT,
  SC_MOON_COMFORT,
  SC_STAR_COMFORT, //220
  SC_FUSION,
  SC_SKILLRATE_UP,
  SC_SKE,
  SC_KAITE,
  SC_SWOO, // [marquis007]
  SC_SKA, // [marquis007]
  SC_EARTHSCROLL,
  SC_MIRACLE, //SG 'hidden' skill [Komurka]
  SC_GS_MADNESSCANCEL,
  SC_GS_ADJUSTMENT, //230
  SC_GS_ACCURACY,
  SC_GS_GATLINGFEVER,
  SC_NJ_TATAMIGAESHI,
  SC_NJ_UTSUSEMI,
  SC_NJ_BUNSINJYUTSU,
  SC_NJ_KAENSIN,
  SC_NJ_SUITON,
  SC_NJ_NEN,
  SC_KNOWLEDGE,
  SC_SMA_READY, //240
  SC_FLING,
  SC_HLIF_AVOID,
  SC_HLIF_CHANGE,
  SC_HAMI_BLOODLUST,
  SC_HLIF_FLEET,
  SC_HLIF_SPEED,
  SC_HAMI_DEFENCE,
  SC_INCASPDRATE,
  SC_PLUSAVOIDVALUE,
  SC_JAILED, //250
  SC_ENCHANTARMS,
  SC_MAGICALATTACK,
  SC_STONESKIN,
  SC_CRITICALWOUND,
  SC_MAGICMIRROR,
  SC_SLOWCAST,
  SC_SUMMER,
  SC_CASH_PLUSEXP,
  SC_CASH_RECEIVEITEM,
  SC_CASH_BOSS_ALARM, //260
  SC_CASH_DEATHPENALTY,
  SC_CRITICALPERCENT,
  //SC_INCDEF,
  //SC_INCBASEATK = 264,
  //SC_FASTCAST,
  SC_PROTECT_MDEF = 266,
  //SC_HPREGEN,
  SC_HEALPLUS = 268,
  SC_PNEUMA,
  SC_AUTOTRADE, //270
  SC_KSPROTECTED,
  SC_ARMOR_RESIST,
  SC_ATKER_BLOOD,
  SC_TARGET_BLOOD,
  SC_TK_SEVENWIND,
  SC_PROTECT_DEF,
  //SC_SPREGEN,
  SC_WALKSPEED = 278,
  // Mercenary Only Bonus Effects
  SC_MER_FLEE,
  SC_MER_ATK, //280
  SC_MER_HP,
  SC_MER_SP,
  SC_MER_HIT,
  SC_MER_QUICKEN,
  SC_REBIRTH,
  //SC_SKILLCASTRATE, //286
  //SC_DEFRATIOATK,
  //SC_HPDRAIN,
  //SC_SKILLATKBONUS,
  //SC_ITEMSCRIPT,
  SC_S_LIFEPOTION = 291,
  SC_L_LIFEPOTION,
  SC_CASH_PLUSONLYJOBEXP,
  //SC_IGNOREDEF,
  SC_HELLPOWER = 295,
  SC_INVINCIBLE,
  SC_INVINCIBLEOFF,
  SC_MANU_ATK,
  SC_MANU_DEF,
  SC_SPL_ATK, //300
  SC_SPL_DEF,
  SC_MANU_MATK,
  SC_SPL_MATK,
  SC_FOOD_STR_CASH,
  SC_FOOD_AGI_CASH,
  SC_FOOD_VIT_CASH,
  SC_FOOD_DEX_CASH,
  SC_FOOD_INT_CASH,
  SC_FOOD_LUK_CASH,
  /**
   * 3rd
   **/
  //SC_FEAR,
  SC_FROSTMISTY = 311,
  /**
   * Rune Knight
   **/
  SC_ENCHANTBLADE,
  SC_DEATHBOUND,
  SC_MILLENNIUMSHIELD,
  SC_CRUSHSTRIKE,
  SC_REFRESH,
  SC_REUSE_REFRESH,
  SC_GIANTGROWTH,
  SC_STONEHARDSKIN,
  SC_VITALITYACTIVATION, // 320
  SC_STORMBLAST,
  SC_FIGHTINGSPIRIT,
  SC_ABUNDANCE,
  /**
   * Arch Bishop
   **/
  SC_ADORAMUS,
  SC_EPICLESIS,
  SC_ORATIO,
  SC_LAUDAAGNUS,
  SC_LAUDARAMUS,
  SC_RENOVATIO,
  SC_EXPIATIO, // 330
  SC_DUPLELIGHT,
  SC_SECRAMENT,
  /**
   * Warlock
   **/
  SC_WHITEIMPRISON,
  SC_MARSHOFABYSS,
  SC_RECOGNIZEDSPELL,
  SC_STASIS,
  SC_SUMMON1,
  SC_SUMMON2,
  SC_SUMMON3,
  SC_SUMMON4, // 340
  SC_SUMMON5,
  SC_READING_SB,
  SC_FREEZINGSP,
  /**
   * Ranger
   **/
  SC_FEARBREEZE,
  SC_ELECTRICSHOCKER,
  SC_WUGDASH,
  SC_WUGBITE,
  SC_CAMOUFLAGE,
  /**
   * Mechanic
   **/
  SC_ACCELERATION,
  SC_HOVERING, // 350
  SC_SHAPESHIFT,
  SC_INFRAREDSCAN,
  SC_ANALYZE,
  SC_MAGNETICFIELD,
  SC_NEUTRALBARRIER,
  SC_NEUTRALBARRIER_MASTER,
  SC_STEALTHFIELD,
  SC_STEALTHFIELD_MASTER,
  SC_OVERHEAT,
  SC_OVERHEAT_LIMITPOINT, // 360
  /**
   * Guillotine Cross
   **/
  SC_VENOMIMPRESS,
  SC_POISONINGWEAPON,
  SC_WEAPONBLOCKING,
  SC_CLOAKINGEXCEED,
  SC_HALLUCINATIONWALK,
  SC_HALLUCINATIONWALK_POSTDELAY,
  SC_ROLLINGCUTTER,
  SC_TOXIN,
  SC_PARALYSE,
  SC_VENOMBLEED, // 370
  SC_MAGICMUSHROOM,
  SC_DEATHHURT,
  SC_PYREXIA,
  SC_OBLIVIONCURSE,
  SC_LEECHESEND,
  /**
   * Royal Guard
   **/
  SC_LG_REFLECTDAMAGE,
  SC_FORCEOFVANGUARD,
  SC_SHIELDSPELL_DEF,
  SC_SHIELDSPELL_MDEF,
  SC_SHIELDSPELL_REF, // 380
  SC_EXEEDBREAK,
  SC_PRESTIGE,
  SC_BANDING,
  SC_BANDING_DEFENCE,
  SC_EARTHDRIVE,
  SC_INSPIRATION,
  /**
   * Sorcerer
   **/
  SC_SPELLFIST,
  //SC_COLD,
  SC_STRIKING = 389,
  SC_WARMER, // 390
  SC_VACUUM_EXTREME,
  SC_PROPERTYWALK,
  /**
   * Minstrel / Wanderer
   **/
  SC_SWING,
  SC_SYMPHONY_LOVE,
  SC_MOONLIT_SERENADE,
  SC_RUSH_WINDMILL,
  SC_ECHOSONG,
  SC_HARMONIZE,
  SC_SIREN,
  //SC_DEEP_SLEEP, // 400
  SC_SIRCLEOFNATURE = 401,
  SC_GLOOMYDAY,
  //SC_GLOOMYDAY_SK,
  SC_SONG_OF_MANA = 404,
  SC_DANCE_WITH_WUG,
  SC_SATURDAY_NIGHT_FEVER,
  SC_LERADS_DEW,
  SC_MELODYOFSINK,
  SC_BEYOND_OF_WARCRY,
  SC_UNLIMITED_HUMMING_VOICE, // 410
  SC_SITDOWN_FORCE,
  SC_NETHERWORLD,
  /**
   * Sura
   **/
  SC_CRESCENTELBOW = 413,
  SC_CURSEDCIRCLE_ATKER,
  SC_CURSEDCIRCLE_TARGET,
  SC_LIGHTNINGWALK,
  SC_RAISINGDRAGON,
  SC_GENTLETOUCH_ENERGYGAIN,
  SC_GENTLETOUCH_CHANGE,
  SC_GENTLETOUCH_REVITALIZE, // 420
  /**
   * Genetic
   **/
  SC_GN_CARTBOOST,
  SC_THORNS_TRAP,
  SC_BLOOD_SUCKER,
  SC_FIRE_EXPANSION_SMOKE_POWDER,
  SC_FIRE_EXPANSION_TEAR_GAS,
  SC_MANDRAGORA,
  SC_STOMACHACHE,
  SC_MYSTERIOUS_POWDER,
  SC_MELON_BOMB,
  SC_BANANA_BOMB, // 430
  SC_BANANA_BOMB_SITDOWN_POSTDELAY,
  SC_SAVAGE_STEAK,
  SC_COCKTAIL_WARG_BLOOD,
  SC_MINOR_BBQ,
  SC_SIROMA_ICE_TEA,
  SC_DROCERA_HERB_STEAMED,
  SC_PUTTI_TAILS_NOODLES,
  SC_BOOST500,
  SC_FULL_SWING_K,
  SC_MANA_PLUS, // 440
  SC_MUSTLE_M,
  SC_LIFE_FORCE_F,
  SC_EXTRACT_WHITE_POTION_Z,
  SC_VITATA_500,
  SC_EXTRACT_SALAMINE_JUICE,
  /**
   * Shadow Chaser
   **/
  SC__REPRODUCE,
  SC__AUTOSHADOWSPELL,
  SC__SHADOWFORM,
  SC__BODYPAINT,
  SC__INVISIBILITY, // 450
  SC__DEADLYINFECT,
  SC__ENERVATION,
  SC__GROOMY,
  SC__IGNORANCE,
  SC__LAZINESS,
  SC__UNLUCKY,
  SC__WEAKNESS,
  SC__STRIPACCESSARY,
  SC__MANHOLE,
  SC__BLOODYLUST, // 460
  /**
   * Elemental Spirits
   **/
  SC_CIRCLE_OF_FIRE,
  SC_CIRCLE_OF_FIRE_OPTION,
  SC_FIRE_CLOAK,
  SC_FIRE_CLOAK_OPTION,
  SC_WATER_SCREEN,
  SC_WATER_SCREEN_OPTION,
  SC_WATER_DROP,
  SC_WATER_DROP_OPTION,
  SC_WATER_BARRIER,
  SC_WIND_STEP, // 470
  SC_WIND_STEP_OPTION,
  SC_WIND_CURTAIN,
  SC_WIND_CURTAIN_OPTION,
  SC_ZEPHYR,
  SC_SOLID_SKIN,
  SC_SOLID_SKIN_OPTION,
  SC_STONE_SHIELD,
  SC_STONE_SHIELD_OPTION,
  SC_POWER_OF_GAIA,
  SC_PYROTECHNIC, // 480
  SC_PYROTECHNIC_OPTION,
  SC_HEATER,
  SC_HEATER_OPTION,
  SC_TROPIC,
  SC_TROPIC_OPTION,
  SC_AQUAPLAY,
  SC_AQUAPLAY_OPTION,
  SC_COOLER,
  SC_COOLER_OPTION,
  SC_CHILLY_AIR, // 490
  SC_CHILLY_AIR_OPTION,
  SC_GUST,
  SC_GUST_OPTION,
  SC_BLAST,
  SC_BLAST_OPTION,
  SC_WILD_STORM,
  SC_WILD_STORM_OPTION,
  SC_PETROLOGY,
  SC_PETROLOGY_OPTION,
  SC_CURSED_SOIL, // 500
  SC_CURSED_SOIL_OPTION,
  SC_UPHEAVAL,
  SC_UPHEAVAL_OPTION,
  SC_TIDAL_WEAPON,
  SC_TIDAL_WEAPON_OPTION,
  SC_ROCK_CRUSHER,
  SC_ROCK_CRUSHER_ATK,
  /* Guild Aura */
  SC_LEADERSHIP,
  SC_GLORYWOUNDS,
  SC_SOULCOLD, // 510
  SC_HAWKEYES,
  /* ... */
  SC_ODINS_POWER,
  /* Sorcerer .extra */
  SC_FIRE_INSIGNIA,
  SC_WATER_INSIGNIA,
  SC_WIND_INSIGNIA,
  SC_EARTH_INSIGNIA,
  /* new pushcart */
  SC_PUSH_CART,
  /* Warlock Spell books */
  SC_SPELLBOOK1,
  SC_SPELLBOOK2,
  SC_SPELLBOOK3, // 520
  SC_SPELLBOOK4,
  SC_SPELLBOOK5,
  SC_SPELLBOOK6,
  /**
   * In official server there are only 7 maximum number of spell books that can be memorized
   * To increase the maximum value just add another status type before SC_SPELLBOOK7 (ex. SC_SPELLBOOK8, SC_SPELLBOOK9 and so on)
   **/
  SC_SPELLBOOK7,
  /* Max HP & SP */
  SC_INCMHP,
  SC_INCMSP,
  SC_PARTYFLEE,
  /**
   * Kagerou & Oboro [malufett]
   **/
  SC_MEIKYOUSISUI,
  SC_KO_JYUMONJIKIRI,
  SC_KYOUGAKU, // 530
  SC_IZAYOI,
  SC_ZENKAI,
  SC_KG_KAGEHUMI,
  SC_KYOMU,
  SC_KAGEMUSYA,
  SC_ZANGETSU,
  SC_GENSOU,
  SC_AKAITSUKI,

  //homon S
  SC_STYLE_CHANGE,
  SC_GOLDENE_FERSE, // 540
  SC_ANGRIFFS_MODUS,
  SC_ERASER_CUTTER,
  SC_OVERED_BOOST,
  SC_LIGHT_OF_REGENE,
  SC_VOLCANIC_ASH,
  SC_GRANITIC_ARMOR,
  SC_MAGMA_FLOW,
  SC_PYROCLASTIC,
  SC_NEEDLE_OF_PARALYZE,
  SC_PAIN_KILLER, // 550

  SC_DARKCROW = 553,
  SC_FULL_THROTTLE,
  SC_REBOUND,
  SC_UNLIMIT,
  SC_KINGS_GRACE,
  SC_TELEKINESIS_INTENSE,
  SC_OFFERTORIUM,
  SC_FRIGG_SONG, // 560

  SC_ALL_RIDING,
  SC_HANBOK,
  SC_MONSTER_TRANSFORM,
  SC_ANGEL_PROTECT,
  SC_ILLUSIONDOPING,

  SC_MTF_ASPD,
  SC_MTF_RANGEATK,
  SC_MTF_MATK,
  SC_MTF_MLEATKED,
  SC_MTF_CRIDAMAGE, // 570

  SC_MOONSTAR,
  SC_SUPER_STAR,

  SC_OKTOBERFEST,
  SC_STRANGELIGHTS,
  SC_DECORATION_OF_MUSIC,

  SC__MAELSTROM,
  SC__CHAOS,

  SC__FEINTBOMB_MASTER,
  SC_FALLENEMPIRE,
  SC_FLASHCOMBO, // 580

  //Vellum Weapon reductions
  SC_DEFSET,
  SC_MDEFSET,

  SC_NO_SWITCH_EQUIP,

  // 2014 Halloween Event
  SC_MTF_MHP,
  SC_MTF_MSP,
  SC_MTF_PUMPKIN,
  SC_MTF_HITFLEE,

  SC_LJOSALFAR,
  SC_MERMAID_LONGING,

  SC_ACARAJE, // 590
  SC_TARGET_ASPD,

  // Geffen Scrolls
  SC_SKELSCROLL,
  SC_DISTRUCTIONSCROLL,
  SC_ROYALSCROLL,
  SC_IMMUNITYSCROLL,
  SC_MYSTICSCROLL,
  SC_BATTLESCROLL,
  SC_ARMORSCROLL,
  SC_FREYJASCROLL,
  SC_SOULSCROLL, // 600

  // Eden Crystal Synthesis
  SC_QUEST_BUFF1,
  SC_QUEST_BUFF2,
  SC_QUEST_BUFF3,

  // Geffen Magic Tournament
  SC_GEFFEN_MAGIC1,
  SC_GEFFEN_MAGIC2,
  SC_GEFFEN_MAGIC3,
  SC_FENRIR_CARD,

  SC_ATKER_ASPD,
  SC_ATKER_MOVESPEED,
  SC_FOOD_CRITICALSUCCESSVALUE, // 610
  SC_CUP_OF_BOZA,
  SC_OVERLAPEXPUP,
  SC_MORA_BUFF,

  // MVP Scrolls
  SC_MVPCARD_TAOGUNKA,
  SC_MVPCARD_MISTRESS,
  SC_MVPCARD_ORCHERO,
  SC_MVPCARD_ORCLORD,

  SC_HAT_EFFECT,
  SC_FLOWERSMOKE,
  SC_FSTONE, // 620
  SC_HAPPINESS_STAR,
  SC_MAPLE_FALLS,
  SC_TIME_ACCESSORY,
  SC_MAGICAL_FEATHER,
  SC_BLOSSOM_FLUTTERING,

  SC_GM_BATTLE,
  SC_GM_BATTLE2,
  SC_2011RWC,
  SC_STR_SCROLL,
  SC_INT_SCROLL, // 630
  SC_STEAMPACK,
  SC_MOVHASTE_POTION,
  SC_MOVESLOW_POTION,
  SC_BUCHEDENOEL,
  SC_PHI_DEMON,
  SC_PROMOTE_HEALTH_RESERCH,
  SC_ENERGY_DRINK_RESERCH,
  SC_MAGIC_CANDY,
  SC_M_LIFEPOTION,
  SC_G_LIFEPOTION, // 640
  SC_MYSTICPOWDER,

  // Summoner
  SC_SUHIDE,
  SC_SU_STOOP,
  SC_SPRITEMABLE,
  SC_CATNIPPOWDER,
  SC_SV_ROOTTWIST,
  SC_BITESCAR,
  SC_ARCLOUSEDASH,
  SC_TUNAPARTY,
  SC_SHRIMP, // 650
  SC_FRESHSHRIMP,

  SC_DRESS_UP,

  // Rodex
  SC_DAILYSENDMAILCNT,

  // Clan System
  SC_CLAN_INFO,

  SC_SIT,
  SC_MOON,
  SC_TING,
  SC_DEVIL1,
  SC_RIDING,
  SC_FALCON,
  SC_WUGRIDER,
  SC_POSTDELAY,
  SC_ON_PUSH_CART,
  SC_RESIST_PROPERTY_WATER,
  SC_RESIST_PROPERTY_GROUND,
  SC_RESIST_PROPERTY_FIRE,
  SC_RESIST_PROPERTY_WIND,
  SC_CLIENT_ONLY_EQUIP_ARROW,
  SC_MADOGEAR,
  SC_POPECOOKIE,
  SC_VITALIZE_POTION,
  SC_SKF_MATK,
  SC_SKF_ATK,
  SC_SKF_ASPD,
  SC_SKF_CAST,
  SC_ALMIGHTY,
  SC_NO_RECOVER_STATE,

  // Rebel
  SC_FALLEN_ANGEL,
  SC_HEAT_BARREL,
  SC_PLATINUM_ALTER,
  SC_ANTI_MATERIAL_BLAST,
  SC_ETERNAL_CHAIN,
  SC_CRIMSON_MARKER,
  SC_QD_SHOT_READY,
  SC_HOWLING_MINE,
  SC_BIND_TRAP,

  // Star Emperor
  SC_SUNSTANCE,
  SC_STARSTANCE,
  SC_LUNARSTANCE,
  SC_NEWMOON,
  SC_FLASHKICK,
  SC_FALLINGSTAR,
  SC_LIGHTOFSUN,
  SC_LIGHTOFMOON,
  SC_LIGHTOFSTAR,
  SC_UNIVERSESTANCE,
  SC_NOVAEXPLOSING,
  SC_GRAVITYCONTROL,
  SC_CREATINGSTAR,
  SC_DIMENSION,
  SC_DIMENSION1,
  SC_DIMENSION2,

  // Soul Emperor
  SC_SOULCOLLECT,
  SC_SOULENERGY,
  SC_SOULREAPER,
  SC_SOULCURSE,
  SC_SP_SHA,
  SC_USE_SKILL_SP_SHA,
  SC_SP_SPA,
  SC_USE_SKILL_SP_SPA,
  SC_SOULUNITY,
  SC_SOULSHADOW,
  SC_SOULFAIRY,
  SC_SOULFALCON,
  SC_SOULGOLEM,
  SC_SOULDIVISION,

  SC_ACTIVE_MONSTER_TRANSFORM,

  SC_FIRE_EXPANSION_TEAR_GAS_SOB,

  SC_TAROTCARD_ATK_PERC,
  SC_TAROTCARD_MATK_PERC,
  SC_TAROTCARD_DEF_PERC,
  SC_GOSPEL_ATK_PERC,
  SC_MAX, //Automatically updated max, used in for's to check we are within bounds.
}
